### ISSUE TITLE
Please add horizontal scrollbar to pinned nodes, quick search and history panels.

### ISSUE THREAD

**Issue by ajaberi1360** [euu2021/Freeplane_UtilityPanels#13]
There is an option in the script settings that can automatically increase the width of these three panels when the mouse is placed on them.
That option is expandedWidthFactorForMasterPanel which is a good option.
Some users may prefer that the width of these panels be fixed, so they should set the number one for the option. So they need a horizontal scroll bar.
Especially for me, who is a right-to-left language, one way to display the text from the beginning of the right is to set the script to automatically move the horizontal scroll bar to the end of the right, in addition to changing the text direction from right to left. So I need a horizontal scroll bar.

**Comment by euu2021** [comment]
Added on 1.14.
