### ISSUE TITLE
Idea: Optimizing panel Layout for Better Space Utilization and Temporal Clarity.

### ISSUE THREAD

**Issue by ajaberi1360** [euu2021/Freeplane_UtilityPanels#4]
"In the image below, I have illustrated the current layout dimensions alongside my proposed design.

In its current state, the plugin wastes a lot of space, which I’ve highlighted in red. You can compare the two images: the design on the left utilizes space more effectively by displaying a greater number of nodes.

In my proposed layout:

Ancestor nodes appear before the selected node, representing their temporal precedence.
Child nodes appear after the selected node, reflecting their temporal delay.
Sibling nodes are placed beside the selected node, which is logical and visually clear.
This arrangement optimizes space usage and improves the readability of the node hierarchy."

![image](https://github.com/user-attachments/assets/ccd87743-950a-48aa-9674-ec92dd7c7aa6)

You might say that the current script for the ancestors and children has more space to display more text. Because they are wider.
In response, we say: Yes, it is true that there is more space for the nodes that have more text, but in return, the width of the sibling panel is small. So, if you assume that you have estimated that the width of the nodes is 90 on average, if you set the value of 90 for the sibling width, the children of the ancestor box will be too large. If you set the width of the children and ancestors box to 90, the width of the sibling will be small.
This means that you have to set the width of the ancestor and child boxes differently than the sibling box.

In the idea that I proposed, the width of the sibling, ancestors, children, and even the selected node can be set to 90.

**Comment by euu2021** [comment]
About the issue: https://github.com/euu2021/Freeplane_UtilityPanels/issues/2

Is it working for you, now? Was [this the solution](https://github.com/euu2021/Freeplane_UtilityPanels/issues/2#issuecomment-2549833409)?

**Comment by euu2021** [comment]
> Is it possible to write a script in such a way that the height of the entire panel changes when there are few nodes in the ancestors, children, siblings panel?

Yes, I will try this, too.

**Comment by euu2021** [comment]
I implemented some changes in the latest version:

The lists height changes according to the number of items. I will make this black space below the lists disappear:

![image](https://github.com/user-attachments/assets/8f355aef-29c6-49bf-997a-2d45e93831e7)
