### ISSUE TITLE
Quick search doesn't work.

### ISSUE THREAD

**Issue by ajaberi1360** [euu2021/Freeplane_UtilityPanels#6]
Currently the jumper is working for me but the quick search panel is not working.
I will explain the installation steps, maybe I did something wrong.

I used Freeplane Portable. You can see the version used.
My installed Java version is OpenJDK22U-jdk_x64_windows_hotspot_22.0.2_9 

![image](https://github.com/user-attachments/assets/fa38d5e2-6c58-4b3f-9cd3-795a63bad03b)

![image](https://github.com/user-attachments/assets/4fc121c1-ed1f-4a37-a10b-e968e6adb626)

![image](https://github.com/user-attachments/assets/39282d39-3344-4c67-88a5-fc54db3333dd)

**Comment by euu2021** [comment]
I will make this integration with the Jumper Add-on be easier to setup.

**Comment by euu2021** [comment]
I will fix it.

**Comment by euu2021** [comment]
Quick search is now working on version 1.13, without the need for Jumper add-on.

I decided to eliminate the Jumper integration and create my own search engine. For now, it's very simple, but I will make it more interesting.
