### ISSUE TITLE
Create a delayed option to run sliding panels instead of directly.

### ISSUE THREAD

**Issue by ajaberi1360** [euu2021/Freeplane_UtilityPanels#7]
The current functionality of the script is that when you hover your mouse over nodes in the slider panel, the pins and history panel, the slider panel is created or updated.
It seems that many people would like to activate the nodes with a time delay that can be configured in the script instead of the direct function.

Suppose someone wants to have the direct function. It is not difficult to set the delay option to one millisecond. One millisecond or the direct option makes no difference.
Therefore, implementing this request practically satisfies everyone's opinion.

**Comment by euu2021** [comment]
Version 1.8 has a selection delay, that can be set at the user settings section.
